# Generated by Django 5.0.4 on 2024-04-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investorproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestor',
            name='customuser',
        ),
        migrations.RemoveField(
            model_name='userinvestor',
            name='investor',
        ),
        migrations.DeleteModel(
            name='InvestorProject',
        ),
        migrations.DeleteModel(
            name='UserInvestor',
        ),
    ]
