version: "3.9"

services:
  postgres_lib:
    image: postgres:latest
    container_name: postgres_lib
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  forum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum
    depends_on:
      - postgres_lib
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  static_volume:
  media_volume:
  postgres_data: