# Generated by Django 5.0.6 on 2024-05-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('projects', '0001_initial'),
        ('startups', '0002_remove_startup_startup_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorNotificationPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_project_profile_change', models.BooleanField(default=True, verbose_name='Email if Project profile changes')),
                ('push_project_profile_change', models.BooleanField(default=True, verbose_name='Push if Project profile changes')),
                ('email_startup_profile_update', models.BooleanField(default=True, verbose_name='Email if Startup profile updates')),
                ('push_startup_profile_update', models.BooleanField(default=True, verbose_name='Push if Startup profile updates')),
                ('investor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_notice_prefs', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('Project follower(s) list changed', 'Project follower(s) list changed'), ('Project subscription changed', 'Project subscription changed'), ('Project profile changed', 'Project profile changed'), ('Startup profile updated', 'Startup profile updated'), ('Startup got new sibscriber', 'Startup got new sibscriber'), ('Startup has lost a sibscriber', 'Startup has lost a sibscriber')], max_length=50)),
                ('initiator', models.CharField(choices=[('investor', 'investor'), ('project', 'project'), ('startup', 'startup')], max_length=8)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_investor', to='investors.investor')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_project', to='projects.project')),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_startup', to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupNotificationPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_project_followers_change', models.BooleanField(default=True, verbose_name='Email on Project followers change')),
                ('email_project_subscription_change', models.BooleanField(default=True, verbose_name='Email on Project subscription change')),
                ('push_project_followers_change', models.BooleanField(default=True, verbose_name='Push on Project followers change')),
                ('push_project_subscription_change', models.BooleanField(default=True, verbose_name='Push on Project subscription change')),
                ('email_startup_subscribed', models.BooleanField(default=True, verbose_name='Email if Startup subscribed')),
                ('email_startup_unsubscribed', models.BooleanField(default=True, verbose_name='Email if Startup unsubscribed')),
                ('push_startup_subscribed', models.BooleanField(default=True, verbose_name='Push if Startup subscribed')),
                ('push_startup_unsubscribed', models.BooleanField(default=True, verbose_name='Push if Startup unsubscribed')),
                ('startup', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_notice_prefs', to='startups.startup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('project__isnull', False), ('investor__isnull', False), _connector='OR'), name='project_or_investor_required'),
        ),
    ]
