# Generated by Django 5.0.4 on 2024-05-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_follower_subscription', models.BooleanField(default=True)),
                ('email_on_share_subscription', models.BooleanField(default=True)),
                ('in_app_on_follower_subscription', models.BooleanField(default=True)),
                ('in_app_on_share_subscription', models.BooleanField(default=True)),
                ('startup', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_preferences', to='startups.startup')),
            ],
        ),
    ]
