# Generated by Django 5.0.6 on 2024-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('Project follower(s) list or subscription share changed', 'Project follower(s) list or subscription share changed'), ('Project profile changed', 'Project profile changed'), ('Startup profile updated', 'Startup profile updated'), ('Startup sibscribers list changed', 'Startup sibscribers list changed')], max_length=55),
        ),
    ]
