# Generated by Django 5.0.6 on 2024-05-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investornotificationprefs',
            old_name='in_app_startup_profile_update',
            new_name='push_startup_profile_update',
        ),
    ]
