# Generated by Django 5.0.6 on 2024-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='email_project_followers_change',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='email_project_subscription_change',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='email_startup_subscribed',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='email_startup_unsubscribed',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='push_project_followers_change',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='push_project_subscription_change',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='push_startup_subscribed',
        ),
        migrations.RemoveField(
            model_name='startupnotificationprefs',
            name='push_startup_unsubscribed',
        ),
        migrations.AddField(
            model_name='startupnotificationprefs',
            name='email_project_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Email on Investor interest in Project change'),
        ),
        migrations.AddField(
            model_name='startupnotificationprefs',
            name='email_startup_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Email on Investor interest in Startup change'),
        ),
        migrations.AddField(
            model_name='startupnotificationprefs',
            name='push_project_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Push on Investor interest in Project change'),
        ),
        migrations.AddField(
            model_name='startupnotificationprefs',
            name='push_startup_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Push on Investor interest in Startup change'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('Project follower list or subscription share change', 'Project follower list or subscription share change'), ('Project profile changed', 'Project profile changed'), ('Startup profile updated', 'Startup profile updated'), ('Startup sibscribers list changed', 'Startup sibscribers list changed')], max_length=55),
        ),
    ]
