# Generated by Django 5.0.6 on 2024-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_startupnotificationprefs_email_project_followers_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investornotificationprefs',
            name='active_email_preferences',
            field=models.CharField(blank=True, default='Project profile changed, Startup profile updated', max_length=50),
        ),
        migrations.AddField(
            model_name='investornotificationprefs',
            name='active_push_preferences',
            field=models.CharField(blank=True, default='Project profile changed, Startup profile updated', max_length=50),
        ),
        migrations.AddField(
            model_name='startupnotificationprefs',
            name='active_email_preferences',
            field=models.CharField(blank=True, default='Project follower list or subscription share change, Startup sibscribers list changed', max_length=100),
        ),
        migrations.AddField(
            model_name='startupnotificationprefs',
            name='active_push_preferences',
            field=models.CharField(blank=True, default='Project follower list or subscription share change, Startup sibscribers list changed', max_length=100),
        ),
    ]
