# Generated by Django 5.0.4 on 2024-05-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreferences',
            old_name='email_on_follower_subscription',
            new_name='email_on_followers_change',
        ),
        migrations.RenameField(
            model_name='notificationpreferences',
            old_name='in_app_on_follower_subscription',
            new_name='in_app_on_followers_change',
        ),
    ]
