# Generated by Django 5.0.4 on 2024-05-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_email_on_follower_subscription_notificationpreferences_email_on_followers_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='email_on_share_subscription',
            field=models.BooleanField(default=True, verbose_name='Subscriptions change email notices'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='in_app_on_share_subscription',
            field=models.BooleanField(default=True, verbose_name='Subscriptions change in_app notices'),
        ),
    ]
