# Generated by Django 5.0.6 on 2024-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_investornotificationprefs_active_email_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investornotificationprefs',
            name='email_project_profile_change',
            field=models.BooleanField(default=True, verbose_name='Email Project changes'),
        ),
        migrations.AlterField(
            model_name='investornotificationprefs',
            name='email_startup_profile_update',
            field=models.BooleanField(default=True, verbose_name='Email Startup updates'),
        ),
        migrations.AlterField(
            model_name='investornotificationprefs',
            name='push_project_profile_change',
            field=models.BooleanField(default=True, verbose_name='Push Project changes'),
        ),
        migrations.AlterField(
            model_name='investornotificationprefs',
            name='push_startup_profile_update',
            field=models.BooleanField(default=True, verbose_name='Push Startup updates'),
        ),
        migrations.AlterField(
            model_name='startupnotificationprefs',
            name='email_project_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Email Investor-Project interest'),
        ),
        migrations.AlterField(
            model_name='startupnotificationprefs',
            name='email_startup_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Email Investor-Startup interest'),
        ),
        migrations.AlterField(
            model_name='startupnotificationprefs',
            name='push_project_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Push Investor-Project interest'),
        ),
        migrations.AlterField(
            model_name='startupnotificationprefs',
            name='push_startup_on_investor_interest_change',
            field=models.BooleanField(default=True, verbose_name='Push Investor-Startup interest'),
        ),
    ]
