
# Generated by Django 5.0.4 on 2024-04-26 16:32



import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_remove_userinvestor_customuser_and_more'),
        ('startups', '0007_delete_userstartup'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_role_id', models.IntegerField()),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='UserStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_role_id', models.IntegerField()),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
