# Generated by Django 5.0.4 on 2024-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userrolecompany_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolecompany',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
