# Generated by Django 5.0.4 on 2024-05-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userrolecompany_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolecompany',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
