# Generated by Django 5.0.4 on 2024-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=150)),
                ('startup_industry', models.CharField(max_length=50)),
                ('startup_phone', models.CharField(max_length=20)),
                ('startup_country', models.CharField(max_length=50)),
                ('startup_city', models.CharField(max_length=50)),
                ('startup_address', models.CharField(max_length=150)),
            ],
        ),
    ]
