# Generated by Django 5.0.4 on 2024-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
