# Generated by Django 5.0.4 on 2024-05-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='startup_prefs',
        ),
    ]
