# Generated by Django 5.0.4 on 2024-04-21 16:33

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_startup_startup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='startup_logo',
            field=models.ImageField(blank=True, null=True, upload_to='startup_logos/'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
