# Generated by Django 5.0.4 on 2024-04-21 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_startup_logo_alter_startup_startup_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/startup_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='Only files with extensions: jpg, jpeg, png, gif are allowed.')]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number must be in the format: '+1234567890'. The Minimum length 9 Maximum length 15 digits.", regex='^\\+1?\\d{9,15}$')]),
        ),
    ]
