# Generated by Django 5.0.4 on 2024-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_alter_startup_id_alter_startup_startup_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
