# Generated by Django 5.0.4 on 2024-04-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_userstartup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStartup',
        ),
    ]
