# Generated by Django 5.0.6 on 2024-05-20 16:44

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=512)),
        ),
    ]
