# Generated by Django 5.0.4 on 2024-04-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0004_alter_startup_id_alter_startup_startup_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=150, unique=True)),
                ('project_status', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='startups.startup')),
            ],
        ),
    ]
