# Generated by Django 5.0.4 on 2024-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='file_description',
            field=models.CharField(db_index=True, max_length=255, verbose_name='file description'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='action',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='change_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
