# Generated by Django 5.0.4 on 2024-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog',
            name='startup_id',
            field=models.IntegerField(db_index=True, default=7),
            preserve_default=False,
        ),
    ]
