# Generated by Django 5.0.4 on 2024-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='startup_id',
            new_name='startup',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
