# Generated by Django 5.0.4 on 2024-04-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_investorproject_investor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorproject',
            options={'ordering': ['project', '-share'], 'verbose_name': 'Project Shortlist', 'verbose_name_plural': 'Project Shortlists'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['startup', 'name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectfiles',
            options={'ordering': ['project'], 'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files'},
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(auto_now_add=True)),
                ('change_time', models.TimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('previous_state', models.CharField(max_length=255)),
                ('modified_state', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_log', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Log',
                'verbose_name_plural': 'Project Logs',
                'ordering': ['-change_date', 'project', 'user_id', 'action'],
            },
        ),
    ]
