# Generated by Django 5.0.4 on 2024-04-25 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_remove_userinvestor_customuser_and_more'),
        ('projects', '0003_rename_startup_id_project_startup_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='investorproject',
            constraint=models.CheckConstraint(check=models.Q(('share__gte', 0), ('share__lte', 100)), name='percentage_share_range'),
        ),
    ]
