# Generated by Django 5.0.4 on 2024-04-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_investorproject_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_log', to='projects.project'),
        ),
    ]
