# Generated by Django 5.0.4 on 2024-04-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectlog_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlog',
            options={'ordering': ['-pk'], 'verbose_name': 'Project Log', 'verbose_name_plural': 'Project Logs'},
        ),
        migrations.AddField(
            model_name='projectlog',
            name='project_title',
            field=models.CharField(default='Some title', max_length=150, verbose_name='Project title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='modified_state',
            field=models.CharField(max_length=255, verbose_name='After changes'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='previous_state',
            field=models.CharField(max_length=255, verbose_name='Before changes'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_log', to='projects.project', verbose_name='Project in DB'),
        ),
    ]
